from flask import Flask, jsonify, redirect, render_template, request, session, url_for
import os
import sqlite3
from datetime import datetime
from functools import wraps

try:
  import psycopg2
  from psycopg2.extras import RealDictCursor
except ImportError:
  psycopg2 = None
  RealDictCursor = None

from werkzeug.security import check_password_hash, generate_password_hash

app = Flask(__name__)
app.secret_key = "omnishop-dev-key-change-me"
ADMIN_EMAIL = "santiavopenso@gmail.com"
DATABASE_URL = os.environ.get("DATABASE_URL")
USAR_POSTGRES = bool(DATABASE_URL)
DB_INTEGRITY_ERROR = (sqlite3.IntegrityError, psycopg2.IntegrityError) if psycopg2 else (sqlite3.IntegrityError,)
DB_ERROR = (sqlite3.Error, psycopg2.Error) if psycopg2 else (sqlite3.Error,)


def conectar_db():
  if USAR_POSTGRES:
    if psycopg2 is None:
      raise RuntimeError("psycopg2-binary no está instalado. Añádelo al requirements.txt para producción.")
    conexion = psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)
    conexion.autocommit = False
    return conexion

  conexion = sqlite3.connect("omnishop.db")
  conexion.row_factory = sqlite3.Row
  return conexion


def obtener_columnas_tabla(cursor, nombre_tabla):
  if USAR_POSTGRES:
    cursor.execute(
      """
      SELECT column_name
      FROM information_schema.columns
      WHERE table_name = %s
      ORDER BY ordinal_position
      """,
      (nombre_tabla,),
    )
    return {fila["column_name"] for fila in cursor.fetchall()}

  columnas = cursor.execute(f"PRAGMA table_info({nombre_tabla})").fetchall()
  return {fila[1] for fila in columnas}


def crear_pk_sql():
  return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if USAR_POSTGRES else "INTEGER PRIMARY KEY AUTOINCREMENT"


def contar_filas(cursor, tabla):
  cursor.execute(f"SELECT COUNT(*) AS total FROM {tabla}")
  fila = cursor.fetchone()
  return fila[0] if isinstance(fila, tuple) else fila["total"]


# Inicializar la base de datos y crear las tablas si no existen
def inicializar_db():
  conexion = conectar_db()
  cursor = conexion.cursor()

  if USAR_POSTGRES:
    cursor.execute("""
      CREATE TABLE IF NOT EXISTS usuarios (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nombre TEXT NOT NULL,
          apellido TEXT NOT NULL DEFAULT '',
          email TEXT,
          password TEXT,
          telefono TEXT NOT NULL DEFAULT '',
          rol TEXT NOT NULL DEFAULT 'cliente',
          correo TEXT,
          contrasena TEXT
      )
    """)
  else:
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nombre TEXT NOT NULL,
            apellido TEXT NOT NULL DEFAULT '',
            email TEXT,
            password TEXT,
            telefono TEXT NOT NULL DEFAULT '',
            rol TEXT NOT NULL DEFAULT 'cliente',
            correo TEXT,
            contrasena TEXT
        )
    """)

  columnas_usuarios = obtener_columnas_tabla(cursor, "usuarios")
  for columna, tipo in (("apellido", "TEXT"), ("email", "TEXT"), ("password", "TEXT"), ("telefono", "TEXT"), ("rol", "TEXT")):
    if columna not in columnas_usuarios:
      cursor.execute(f"ALTER TABLE usuarios ADD COLUMN {columna} {tipo} NOT NULL DEFAULT ''")
  cursor.execute("UPDATE usuarios SET email = COALESCE(NULLIF(email, ''), correo)")
  cursor.execute("UPDATE usuarios SET password = COALESCE(NULLIF(password, ''), contrasena)")
  cursor.execute("UPDATE usuarios SET rol = 'cliente' WHERE rol IS NULL OR rol = ''")
  cursor.execute("SELECT id FROM usuarios ORDER BY id LIMIT 1")
  primer_usuario = cursor.fetchone()
  if primer_usuario:
    if isinstance(primer_usuario, dict):
      primer_id = primer_usuario["id"]
    else:
      primer_id = primer_usuario[0]
    cursor.execute("UPDATE usuarios SET rol = 'admin' WHERE id = %s", (primer_id,)) if USAR_POSTGRES else cursor.execute("UPDATE usuarios SET rol = 'admin' WHERE id = ?", (primer_id,))
  cursor.execute("UPDATE usuarios SET rol = 'admin' WHERE lower(email) = lower(%s)", (ADMIN_EMAIL,)) if USAR_POSTGRES else cursor.execute("UPDATE usuarios SET rol = 'admin' WHERE lower(email) = lower(?)", (ADMIN_EMAIL,))
  cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email)")

  cursor.execute(
    f"""
      CREATE TABLE IF NOT EXISTS productos (
          id {crear_pk_sql()},
          nombre TEXT NOT NULL,
          precio REAL NOT NULL,
          stock INTEGER NOT NULL,
          imagen TEXT
      )
    """
  )

  cursor.execute(
    f"""
      CREATE TABLE IF NOT EXISTS pedidos (
          id {crear_pk_sql()},
          usuario_id INTEGER,
          fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
          total REAL NOT NULL,
          direccion TEXT NOT NULL DEFAULT '',
          estado TEXT NOT NULL DEFAULT 'registrado',
          FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
      )
    """
  )
  columnas_pedidos = obtener_columnas_tabla(cursor, "pedidos")
  if "direccion" not in columnas_pedidos:
    cursor.execute("ALTER TABLE pedidos ADD COLUMN direccion TEXT NOT NULL DEFAULT ''")

  cursor.execute(
    f"""
      CREATE TABLE IF NOT EXISTS detalle_pedidos (
          id {crear_pk_sql()},
          pedido_id INTEGER NOT NULL,
          producto_id INTEGER NOT NULL,
          cantidad INTEGER NOT NULL CHECK (cantidad > 0),
          precio_unitario REAL NOT NULL,
          FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
          FOREIGN KEY (producto_id) REFERENCES productos(id)
      )
    """
  )

  conexion.commit()

  cantidad = contar_filas(cursor, "productos")
  if cantidad == 0:
    if USAR_POSTGRES:
      cursor.execute(
          "INSERT INTO productos (nombre, precio, stock, imagen) VALUES (%s, %s, %s, %s)",
          ("Monitor 24\" FHD 180Hz", 139.0, 38, "img/monitor.jpg"),
      )
      cursor.execute(
          "INSERT INTO productos (nombre, precio, stock, imagen) VALUES (%s, %s, %s, %s)",
          ("Headset Gamer 7.1", 79.0, 28, "img/headset.jpg"),
      )
    else:
      cursor.execute(
          "INSERT INTO productos (nombre, precio, stock, imagen) VALUES (?, ?, ?, ?)",
          ("Monitor 24\" FHD 180Hz", 139.0, 38, "img/monitor.jpg"),
      )
      cursor.execute(
          "INSERT INTO productos (nombre, precio, stock, imagen) VALUES (?, ?, ?, ?)",
          ("Headset Gamer 7.1", 79.0, 28, "img/headset.jpg"),
      )
    conexion.commit()

  productos_catalogo = [
    ("RTX 5070 Ti 16GB", 899, 14, "img/GeForce-RTX™-5070-Ti-WINDFORCE-OC-SFF-16G-01.png"),
    ("RTX 4060 8GB", 299, 32, "img/images (3).jpg"),
    ("Ryzen 7 7800X3D", 369, 21, "img/51HqC0rU9HL._AC_SL1500_.jpg"),
    ("Ryzen 5 7600", 199, 40, "img/D_NQ_NP_719037-MLA99972093783_112025-O.webp"),
    ("Vengeance 32GB DDR5 6000", 109, 48, "img/20-236-909-02_square.jpg"),
    ("990 EVO Plus 1TB NVMe", 89, 55, "img/Samsung_1TB_990_EVO_Plus_BOX_1000x_02e0faf0-37cb-4fc2-8275-c58fdfb584fb.webp"),
    ("ROG Strix G16", 1249, 9, "img/images.jpg"),
    ("IdeaPad Slim 5", 649, 17, "img/w=1500,h=1500,fit=cover.webp"),
    ("Monitor 27\" QHD 165Hz", 279, 26, "img/images (1).jpg"),
    ("Monitor 34\" Ultrawide 144Hz", 449, 12, "img/images (5).jpg"),
    ("Teclado mecánico 75% RGB", 99, 33, "img/images (2).jpg"),
    ("Mouse inalámbrico 26K DPI", 59, 60, "img/D_NQ_NP_607996-MLA100010457619_122025-O.webp"),
    ("Headset gamer 7.1", 79, 28, "img/1_bf44a5e1-bfad-426b-9666-9ab7b10ee719.webp"),
    ("Fuente 850W 80+ Gold", 119, 22, "img/D_NQ_NP_930241-MLA99522507928_122025-O.webp"),
    ("Refrigeración líquida 240mm RGB", 89, 18, "img/images (6).jpg"),
  ]
  for producto in productos_catalogo:
    if USAR_POSTGRES:
      cursor.execute(
        "SELECT 1 FROM productos WHERE LOWER(nombre) = LOWER(%s) LIMIT 1",
        (producto[0],),
      )
      existe = cursor.fetchone()
    else:
      cursor.execute(
        "SELECT 1 FROM productos WHERE nombre = ? COLLATE NOCASE LIMIT 1",
        (producto[0],),
      )
      existe = cursor.fetchone()
    if not existe:
      if USAR_POSTGRES:
        cursor.execute(
          "INSERT INTO productos (nombre, precio, stock, imagen) VALUES (%s, %s, %s, %s)",
          producto,
        )
      else:
        cursor.execute(
          "INSERT INTO productos (nombre, precio, stock, imagen) VALUES (?, ?, ?, ?)",
          producto,
        )
  conexion.commit()

  conexion.close()


inicializar_db()


def requiere_login(view):
  @wraps(view)
  def wrapped_view(*args, **kwargs):
    if "usuario_id" not in session:
      return jsonify({"error": "Debes iniciar sesión para consultar tus pedidos."}), 401
    return view(*args, **kwargs)

  return wrapped_view


def requiere_admin(view):
  @wraps(view)
  def wrapped_view(*args, **kwargs):
    if "usuario_id" not in session:
      return redirect(url_for("login", next=request.path))
    if session.get("usuario_rol") != "admin":
      return "No tienes permisos para acceder a esta sección.", 403
    return view(*args, **kwargs)

  return wrapped_view


# Ruta principal (Muestra la tienda y los productos)
@app.route("/")
def index():
  conexion = conectar_db()
  try:
    with conexion.cursor() as cursor:
      cursor.execute("SELECT * FROM productos")
      productos = cursor.fetchall()
  finally:
    conexion.close()
  return render_template("index.html", productos=[dict(producto) for producto in productos])


@app.route("/carrito")
def carrito():
  if "usuario_id" not in session:
    return redirect(url_for("login", next="/carrito"))
  return render_template("carrito.html")


@app.route("/perfil", methods=["GET", "POST"])
@requiere_login
def perfil():
  conexion = conectar_db()
  try:
    with conexion.cursor() as cursor:
      cursor.execute(
        "SELECT id, nombre, apellido, email, telefono, rol FROM usuarios WHERE id = %s" if USAR_POSTGRES else "SELECT id, nombre, apellido, email, telefono, rol FROM usuarios WHERE id = ?",
        (session["usuario_id"],),
      )
      usuario = cursor.fetchone()
    if usuario is None:
      conexion.close()
      session.clear()
      return redirect(url_for("login"))
    error = None
    mensaje = None
    if request.method == "POST":
      nombre = request.form.get("nombre", "").strip()
      apellido = request.form.get("apellido", "").strip()
      email = request.form.get("email", "").strip().lower()
      telefono = request.form.get("telefono", "").strip()
      nueva_password = request.form.get("password", "")
      if not nombre or not apellido or not email:
        error = "Nombre, apellido y correo son obligatorios."
      elif nueva_password and len(nueva_password) < 6:
        error = "La nueva contraseña debe tener al menos 6 caracteres."
      else:
        try:
          with conexion.cursor() as cursor:
            if USAR_POSTGRES:
              cursor.execute(
                "UPDATE usuarios SET nombre = %s, apellido = %s, email = %s, telefono = %s, correo = %s, password = %s, contrasena = %s, rol = CASE WHEN rol = 'admin' OR LOWER(%s) = LOWER(%s) THEN 'admin' ELSE rol END WHERE id = %s",
                (nombre, apellido, email, telefono, email, generate_password_hash(nueva_password) if nueva_password else usuario["password"], generate_password_hash(nueva_password) if nueva_password else usuario["password"], email, ADMIN_EMAIL, session["usuario_id"]),
              )
            else:
              cursor.execute(
                "UPDATE usuarios SET nombre = ?, apellido = ?, email = ?, telefono = ?, correo = ?, password = ?, contrasena = ?, rol = CASE WHEN rol = 'admin' OR lower(?) = lower(?) THEN 'admin' ELSE rol END WHERE id = ?",
                (nombre, apellido, email, telefono, email, generate_password_hash(nueva_password) if nueva_password else usuario["password"], generate_password_hash(nueva_password) if nueva_password else usuario["password"], email, ADMIN_EMAIL, session["usuario_id"]),
              )
            conexion.commit()
            session["usuario_nombre"] = nombre
            session["usuario_correo"] = email
            mensaje = "Datos actualizados correctamente."
            cursor.execute(
              "SELECT id, nombre, apellido, email, telefono, rol FROM usuarios WHERE id = %s" if USAR_POSTGRES else "SELECT id, nombre, apellido, email, telefono, rol FROM usuarios WHERE id = ?",
              (session["usuario_id"],),
            )
            usuario = cursor.fetchone()
        except DB_INTEGRITY_ERROR:
          conexion.rollback()
          error = "Ese correo ya está registrado por otro usuario."
    return render_template("perfil.html", usuario=usuario, error=error, mensaje=mensaje)
  finally:
    conexion.close()


@app.route("/api/checkout", methods=["POST"])
def checkout():
  if "usuario_id" not in session:
    return jsonify({"error": "Debes iniciar sesión antes de comprar.", "login_url": url_for("login", next="/carrito")}), 401
  payload = request.get_json(silent=True) or {}
  raw_items = payload.get("items", [])
  direccion = str(payload.get("direccion", "")).strip()
  if not isinstance(raw_items, list) or not raw_items:
    return jsonify({"error": "El carrito está vacío."}), 400
  if len(direccion) < 8:
    return jsonify({"error": "Indica una dirección de entrega válida."}), 400

  conexion = conectar_db()
  try:
    with conexion.cursor() as cursor:
      if not USAR_POSTGRES:
        cursor.execute("BEGIN IMMEDIATE")
      else:
        cursor.execute("BEGIN")
      cantidades = {}
      for item in raw_items:
        cantidad = item.get("cantidad", item.get("qty"))
        nombre = item.get("nombre")
        try:
          cantidad = int(cantidad)
        except (TypeError, ValueError):
          return jsonify({"error": "La cantidad de un producto no es válida."}), 400
        if cantidad <= 0 or not nombre:
          return jsonify({"error": "Cada producto debe tener nombre y cantidad positiva."}), 400
        cantidades[nombre] = cantidades.get(nombre, 0) + cantidad

      productos = []
      for nombre, cantidad in cantidades.items():
        if USAR_POSTGRES:
          cursor.execute(
            "SELECT id, nombre, precio, stock FROM productos WHERE LOWER(nombre) = LOWER(%s) ORDER BY id LIMIT 1",
            (nombre,),
          )
          producto = cursor.fetchone()
        else:
          cursor.execute(
            "SELECT id, nombre, precio, stock FROM productos WHERE nombre = ? COLLATE NOCASE ORDER BY id LIMIT 1",
            (nombre,),
          )
          producto = cursor.fetchone()
        if producto is None:
          return jsonify({"error": f"El producto '{nombre}' no existe en el inventario."}), 404
        if producto["stock"] < cantidad:
          return jsonify({"error": f"Stock insuficiente para '{nombre}'. Disponible: {producto['stock']}."}), 409
        productos.append((producto, cantidad))

      subtotal = sum(producto["precio"] * cantidad for producto, cantidad in productos)
      envio = 0 if subtotal >= 99 else 9.99
      total = round(subtotal + envio, 2)
      if USAR_POSTGRES:
        cursor.execute(
          "INSERT INTO pedidos (usuario_id, total, direccion) VALUES (%s, %s, %s) RETURNING id",
          (session["usuario_id"], total, direccion),
        )
        pedido_id = cursor.fetchone()["id"]
      else:
        cursor.execute(
          "INSERT INTO pedidos (usuario_id, total, direccion) VALUES (?, ?, ?)",
          (session["usuario_id"], total, direccion),
        )
        pedido_id = cursor.lastrowid

      for producto, cantidad in productos:
        if USAR_POSTGRES:
          cursor.execute(
            "INSERT INTO detalle_pedidos (pedido_id, producto_id, cantidad, precio_unitario) VALUES (%s, %s, %s, %s)",
            (pedido_id, producto["id"], cantidad, producto["precio"]),
          )
        else:
          cursor.execute(
            "INSERT INTO detalle_pedidos (pedido_id, producto_id, cantidad, precio_unitario) VALUES (?, ?, ?, ?)",
            (pedido_id, producto["id"], cantidad, producto["precio"]),
          )
        if USAR_POSTGRES:
          cursor.execute(
            "UPDATE productos SET stock = stock - %s WHERE id = %s AND stock >= %s",
            (cantidad, producto["id"], cantidad),
          )
        else:
          cursor.execute(
            "UPDATE productos SET stock = stock - ? WHERE id = ? AND stock >= ?",
            (cantidad, producto["id"], cantidad),
          )

      conexion.commit()
      usuario = session.get("usuario_correo") or session.get("usuario_id") or "invitado"
      fecha_compra = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
      detalle_venta = ", ".join(
        f"{producto['nombre']} (cantidad: {cantidad})"
        for producto, cantidad in productos
      )
      with open("ventas.txt", "a", encoding="utf-8") as archivo_ventas:
        archivo_ventas.write(
          f"Fecha: {fecha_compra}\n"
          f"Usuario: {usuario}\n"
          f"Productos: {detalle_venta}\n"
          f"Dirección de entrega: {direccion}\n"
          f"Total pagado: ${total:.2f}\n"
          f"Pedido: #{pedido_id}\n"
          "----------------------------------------\n"
        )
    return jsonify({"pedido_id": pedido_id, "total": total}), 201
  except DB_ERROR:
    conexion.rollback()
    return jsonify({"error": "No fue posible registrar el pedido."}), 500
  finally:
    conexion.close()


@app.route("/mis-pedidos")
def mis_pedidos():
  if "usuario_id" not in session:
    return render_template("mis_pedidos.html", pedidos=[], detalles={}, requiere_login=True)
  conexion = conectar_db()
  try:
    with conexion.cursor() as cursor:
      if USAR_POSTGRES:
        cursor.execute(
          "SELECT id, fecha, total, direccion, estado FROM pedidos WHERE usuario_id = %s ORDER BY fecha DESC, id DESC",
          (session["usuario_id"],),
        )
      else:
        cursor.execute(
          "SELECT id, fecha, total, direccion, estado FROM pedidos WHERE usuario_id = ? ORDER BY fecha DESC, id DESC",
          (session["usuario_id"],),
        )
      pedidos = cursor.fetchall()

      if USAR_POSTGRES:
        cursor.execute(
          """
          SELECT d.pedido_id, p.nombre, d.cantidad, d.precio_unitario
          FROM detalle_pedidos d
          JOIN pedidos pe ON pe.id = d.pedido_id
          JOIN productos p ON p.id = d.producto_id
          WHERE pe.usuario_id = %s
          ORDER BY d.id
          """,
          (session["usuario_id"],),
        )
      else:
        cursor.execute(
          """
          SELECT d.pedido_id, p.nombre, d.cantidad, d.precio_unitario
          FROM detalle_pedidos d
          JOIN pedidos pe ON pe.id = d.pedido_id
          JOIN productos p ON p.id = d.producto_id
          WHERE pe.usuario_id = ?
          ORDER BY d.id
          """,
          (session["usuario_id"],),
        )
      detalles = cursor.fetchall()
  finally:
    conexion.close()
  detalles_por_pedido = {}
  for detalle in detalles:
    detalles_por_pedido.setdefault(detalle["pedido_id"], []).append(detalle)
  return render_template("mis_pedidos.html", pedidos=pedidos, detalles=detalles_por_pedido, requiere_login=False)


@app.route("/admin/inventario", methods=["GET", "POST"])
@requiere_admin
def inventario():
  conexion = conectar_db()
  try:
    with conexion.cursor() as cursor:
      producto_id = request.form.get("producto_id", type=int)
      if request.method == "POST":
        delta = request.form.get("delta", type=int)
        stock = request.form.get("stock", type=int)
        if producto_id is None or (delta is None and (stock is None or stock < 0)):
          return "El producto y el stock deben ser válidos.", 400
        if delta is not None:
          if USAR_POSTGRES:
            cursor.execute(
              "UPDATE productos SET stock = GREATEST(0, stock + %s) WHERE id = %s",
              (delta, producto_id),
            )
          else:
            cursor.execute(
              "UPDATE productos SET stock = MAX(0, stock + ?) WHERE id = ?",
              (delta, producto_id),
            )
        else:
          if USAR_POSTGRES:
            cursor.execute("UPDATE productos SET stock = %s WHERE id = %s", (stock, producto_id))
          else:
            cursor.execute("UPDATE productos SET stock = ? WHERE id = ?", (stock, producto_id))
        conexion.commit()
      cursor.execute("SELECT id, nombre, precio, stock FROM productos ORDER BY nombre")
      productos = cursor.fetchall()
    return render_template("inventario.html", productos=productos)
  finally:
    conexion.close()


@app.route("/admin/usuarios", methods=["GET", "POST"])
@requiere_admin
def admin_usuarios():
  conexion = conectar_db()
  try:
    if request.method == "POST":
      usuario_id = request.form.get("usuario_id", type=int)
      if usuario_id == session["usuario_id"]:
        return "No puedes eliminar tu propia cuenta de administrador.", 400
      try:
        with conexion.cursor() as cursor:
          if USAR_POSTGRES:
            cursor.execute(
              "DELETE FROM detalle_pedidos WHERE pedido_id IN (SELECT id FROM pedidos WHERE usuario_id = %s)",
              (usuario_id,),
            )
            cursor.execute("DELETE FROM pedidos WHERE usuario_id = %s", (usuario_id,))
            cursor.execute("DELETE FROM usuarios WHERE id = %s", (usuario_id,))
          else:
            cursor.execute(
              "DELETE FROM detalle_pedidos WHERE pedido_id IN (SELECT id FROM pedidos WHERE usuario_id = ?)",
              (usuario_id,),
            )
            cursor.execute("DELETE FROM pedidos WHERE usuario_id = ?", (usuario_id,))
            cursor.execute("DELETE FROM usuarios WHERE id = ?", (usuario_id,))
          conexion.commit()
      except DB_ERROR:
        conexion.rollback()
        return "No fue posible eliminar el usuario.", 500
    with conexion.cursor() as cursor:
      cursor.execute(
        "SELECT id, nombre, apellido, email, telefono, rol FROM usuarios ORDER BY id"
      )
      usuarios = cursor.fetchall()
    return render_template("admin_usuarios.html", usuarios=usuarios)
  finally:
    conexion.close()


@app.route("/login", methods=["GET", "POST"])
def login():
  if request.method == "GET":
    return render_template("login.html", next_url=request.args.get("next", "/"))
  correo = request.form.get("email", request.form.get("correo", "")).strip().lower()
  contrasena = request.form.get("password", request.form.get("contrasena", ""))
  conexion = conectar_db()
  try:
    with conexion.cursor() as cursor:
      if USAR_POSTGRES:
        cursor.execute("SELECT * FROM usuarios WHERE LOWER(email) = LOWER(%s)", (correo,))
      else:
        cursor.execute("SELECT * FROM usuarios WHERE email = ? COLLATE NOCASE", (correo,))
      usuario = cursor.fetchone()
  finally:
    conexion.close()
  if not usuario or not check_password_hash(usuario["password"], contrasena):
    return render_template("login.html", error="Correo o contraseña incorrectos.", next_url=request.form.get("next", "/")), 401
  session["usuario_id"] = usuario["id"]
  session["usuario_nombre"] = usuario["nombre"]
  session["usuario_correo"] = usuario["email"]
  rol = "admin" if correo == ADMIN_EMAIL else usuario["rol"]
  if rol == "admin" and usuario["rol"] != "admin":
    conexion = conectar_db()
    try:
      with conexion.cursor() as cursor:
        if USAR_POSTGRES:
          cursor.execute("UPDATE usuarios SET rol = 'admin' WHERE id = %s", (usuario["id"],))
        else:
          cursor.execute("UPDATE usuarios SET rol = 'admin' WHERE id = ?", (usuario["id"],))
        conexion.commit()
    finally:
      conexion.close()
  session["usuario_rol"] = rol
  return redirect(request.form.get("next") or url_for("index"))


@app.route("/logout", methods=["POST"])
def logout():
  session.clear()
  return redirect(url_for("index"))


# Ruta para procesar el Registro de Usuarios
@app.route("/registro", methods=["GET", "POST"])
def registro():
  if request.method == "GET":
    return render_template("registro.html", next_url=request.args.get("next", "/"))
  nombre = request.form.get("nombre", "").strip()
  apellido = request.form.get("apellido", "").strip()
  correo = request.form.get("email", request.form.get("correo", "")).strip().lower()
  contrasena = request.form.get("password", request.form.get("contrasena", ""))
  telefono = request.form.get("telefono", "").strip()
  if not nombre or not apellido or not correo or len(contrasena) < 6:
    return render_template("registro.html", error="Completa todos los campos y usa una contraseña de al menos 6 caracteres.", next_url=request.form.get("next", "/")), 400

  try:
    conexion = conectar_db()
    try:
      with conexion.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM usuarios")
        resultado = cursor.fetchone()
        cantidad_usuarios = resultado[0] if not isinstance(resultado, dict) else resultado.get("count")
        rol = "admin" if cantidad_usuarios == 0 or correo == ADMIN_EMAIL else "cliente"
        if USAR_POSTGRES:
          cursor.execute(
            "INSERT INTO usuarios (nombre, apellido, email, password, telefono, rol, correo, contrasena) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
            (nombre, apellido, correo, generate_password_hash(contrasena), telefono, rol, correo, generate_password_hash(contrasena)),
          )
        else:
          cursor.execute(
            "INSERT INTO usuarios (nombre, apellido, email, password, telefono, rol, correo, contrasena) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (nombre, apellido, correo, generate_password_hash(contrasena), telefono, rol, correo, generate_password_hash(contrasena)),
          )
        conexion.commit()
      return redirect(url_for("login", next=request.form.get("next", "/")))
    except DB_INTEGRITY_ERROR:
      conexion.rollback()
      return render_template("registro.html", error="Ese correo ya está registrado.", next_url=request.form.get("next", "/")), 409
  finally:
    conexion.close()


if __name__ == "__main__":
  inicializar_db()  # Crea la BD y mete los productos de prueba al arrancar
  app.run(debug=True)